name: test
on: [push, pull_request]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone submodules
        run: git submodule update --recursive --init
      - name: Run tests
        run: make test
